### ISSUE TITLE
ImportError: cannot import name "url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by Ston3Cold** [michal-kapala/gsconnect#10]
Hello,

Sorry for creating another issue. I've followed the steps you outlined and I installed all the dependencies using the requirements.txt. When trying to launch the gsconnect.py file however I'm get the following:

![Error](https://github.com/user-attachments/assets/1e4af6c5-4d09-4959-aa0d-eed73916fa8c)

Any idea what it could be, or what I'm doing wrong?

**Comment by michal-kapala** [comment]
@Ston3Cold this was Flask's [dependency issue](https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr) on the underlying Werkzeug library that should hopefully be fixed now, install the dependencies again before you run the latest version.

**Comment by Ston3Cold** [comment]
Thanks a lot, I'll give it a try once I'm back home from a business trip - appreciate the reply!

**Comment by Ston3Cold** [comment]
I managed to get it working after adding and updating the dependencies - It's a pity that it doesn't work with the games I've tried (Rainbow Six Vegas 1 and 2) - but I know the code will need modifications/additions to make it perhaps compatible with other titles. Thanks again :)

**Comment by Joshhhuaaa** [comment]
> I managed to get it working after adding and updating the dependencies - It's a pity that it doesn't work with the games I've tried (Rainbow Six Vegas 1 and 2) - but I know the code will need modifications/additions to make it perhaps compatible with other titles. Thanks again :)

Rainbow Six Vegas (and Vegas 2) do not use Ubisoft Game Service, those games use Demonware. [Here](https://gist.github.com/Joshhhuaaa/94579e63e52eea8c8d2a90f6f8a53b34) is a list of games that will likely be compatible.
