### ISSUE TITLE
Guide on how to compile/run/utilize the emulator

### ISSUE THREAD

**Issue by Ston3Cold** [michal-kapala/gsconnect#9]
Hi there,

Sorry for creating an "issue", but would you mind providing a tutorial on how to get this up and running on a Windows machine? I'm quite interested in trying it out. I've got python installed, but once it comes to pip and flask and I completely lost.

Another question that I have, do support for games have to be added to the code of the emulator for it to work? Or can one test multiple games to see what is compatible and what isn't?

Thanks,
SC

**Comment by michal-kapala** [comment]
PIP gets installed with standard Python distros, if you dont have a PATH environment variable for it you should add the path to `pip.exe` there first.

To run gsconnect web service run this from the project's root dir:
```
pip install -r requirements.txt
cd gsconnect
python gsconnect.py
```
This downloads all the needed dependencies and starts the gsconnect server emu on port 80 (http).

**Comment by michal-kapala** [comment]
The web service should work with every GS game, as for the game servers currently the one in development is built for heroes of might and magic 5 but majority of the code appeared to be compatible with splinter cell chaos theory so definitely can be toyed with for other titles

**Comment by Ston3Cold** [comment]
Thanks a lot for the quick reply. I'll try out what you said, sounds / seem straight forward enough. And yeah, I wouldn't mind test as many games as I possibly can to see what works and what doesn't work. 

If I do encounter working titles, I'll be sure to make a list, that way we can update the list of supported games. Thanks for creating this, I'm always in awe of emu projects such as these and wish that I too had the knowledge to do something similar.

Keep up the great work :)
